### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by sugarshin**
Hi,

I fixed dependencies.

- `prop-types` should into `dependecies`
- should not `@types/react-image-crop` into the `dependecies` because not needed in production

Thank you.

### CODE REVIEW

**Comment by DominicTobias** [comment]
Hi thanks but prop-types is declared as a peer dependency by design - your app should install it, this avoids duplication in the final bundle.

Types are also intentionally there and do not get built into the bundle, but they are installed for people you use typescript without they themselves having to manually install it. For those not using it, it’s a tiny package which does not get used so not a big deal I think?

**Comment by sugarshin** [comment]
Hi, Dominic.
Depending on the project, prop-types may not be necessary. And even small libraries as small as prop-types do not matter if they duplicate.
Including @types in dependencies is rare. And, it should be installed by the person who wants to use it. Otherwise type should be created in this repository.

**Comment by DominicTobias** [comment]
I don't really have an issue with moving proptypes to deps if you like, but would like to leave types there since people are depending on it being there (https://github.com/DominicTobias/react-image-crop/pull/200) and it wouldn't make sense for types to go missing in a patch or minor version change. Besides it is a small module which doesn't effect people who are not using it.

**Comment by sugarshin** [comment]
OK, I will fix it later. Thank you!

**Comment by sugarshin** [comment]
@DominicTobias I fixed it.

**Comment by sugarshin** [comment]
By the way, the latest version of `@types/react-image-crop` is `v6.0.1`. You must also follow this update if you include it in the dependencies of this repository. After all, it is not a good idea. I think that I should get rid of this dependency even if I upgrade the major version.

**Comment by DominicTobias** [comment]
Agreed, I will remove in next major version which I'm planning to do fairly soon. I intend to change the cropping library to use pixels rather than percentages as it causes more trouble than it's worth

Will update to v6 for now

**Comment by DominicTobias** [comment]
Updated in v7 so that it is not a depedency, also PropTypes is no longer a peer dep. Note that v7 has breaking changes though.

**Pull request merged**
