### PR TITLE
Feature: Keep selection when user clicks out of the cropping area

### PR DESCRIPTION
**Pull request by DPr00f**
Hi @DominicTobias ,
Here are the changes that contain the new feature. Enable/Disable selection area when clicking outside the cropping area.
Just to keep track, this is related to the PR #11

### CODE REVIEW

**Comment by DominicTobias** [comment]
Perfect, thanks!

**Comment by DominicTobias** [comment]
Published as 0.0.14

**Comment by DPr00f** [comment]
Nice, thanks.
As a general idea, would be nice to not have to build every time a PR is made.
Specially because after the first merge, it will probably impede the other PR to be merged.
Do you think you could ignore ./dist/ and on npm prepublish do "npm release"?
Same goes for ignoring dev/bundle.js
I think it would keep the repo cleaner, and anyone doing a PR does need to care about building it

**Comment by DominicTobias** [comment]
Yeah I agree, the mechanism is pretty basic and could use improvement, running release on publish sounds like a good idea to me

**Comment by DPr00f** [comment]
To be fair, Github is pretty good to keep track of the contributors

**Pull request merged**
