### PR TITLE
BugFix: Cropping Area Disappearing on mouse click

### PR DESCRIPTION
**Pull request by DPr00f**
Hi @DominicTobias 
Came across another bug today that leads to the cropping area disappearing when clicking outside of the cropped area.
Here's a gif explaining the problem
newbug

When clicking outside of the cropped area the library is overriding this.state.crop, which leads to undesirable results. With this PR that will be fixed and the dragCrop and resizeCrop will still work

newbugfix

On the same pull request I've took the liberty to fix the webpack which was causing me some errors and refused to render the ReactCropper.jsx

I used you're very own sample to test the Library and make sure the issue disappeared.

### CODE REVIEW

**Comment by DominicTobias** [comment]
Thanks @DPr00f, actually this one is desired behaviour - the Photoshop selection tool does the same think (well when you're not transforming a selection to be fair), but actually the behaviour is influenced by jCrop which is probably the most widely used web cropping lib: http://deepliquid.com/projects/Jcrop/demos.php. Neither is wrong really I just went with what the user it probably more familiar with.

But thanks for the other updates I'll commit those now.

**Comment by DominicTobias** [comment]
If you'd like to make this a non-default option pass with a prop I can add that

**Comment by DPr00f** [comment]
Yeah. That would be awesome actually, cause you might want to force a user to crop an image, specially with an aspect passed through. Do you want me to do those changes? Like, props.alwaysSelected which would default to false?
If you want you can do the changes yourself, probably makes more sense since you know exactly the requirements. Either way let me know if I can help.
Cheers

**Comment by DominicTobias** [comment]
Just to be clear, when they click and drag another part of the image the
same aspect that was previously set is maintained isn't it? (I hope so else
it's a bug).

Perhaps keepSelection and default to false. Feel free to add it, otherwise
I can add it no prob (but tomorrow as I'm going to bed now).

**Comment by DPr00f** [comment]
Yeah, when they click and drag the same aspect ratio is kept. Cool I'll do
it then and I'll open the PR. Feel free to take a look when you have some
time. I'll close this one as it's not really a bug.
Thanks

**Pull request closed without merging**
