### PR TITLE
Add prop to disable crossover if minWidth/minHeight is used

### PR DESCRIPTION
**Pull request by tudorpavel**
Relates to discussion in #206.

We could also consider disabling crossover by default if `minWidth` or `minHeight` is used. In my opinion, it's useless to flip/invert if there is a minimum rectangle allowed and it could simplify the crossover code.

What do you think?

### CODE REVIEW

**Comment by DominicTobias** [comment]
Thanks for this @tudorpavel, I agree it's not needed and can be off by default if both minWidth and minHeight are used, but would need to check behaviour if only one is set. I'll leave open just for now to see if we can just do it by default.

**Comment by tudorpavel** [comment]
@DominicTobias nice, having it disabled by default would be great.

I will also test this some more... It seems what I did is not enough to disable the functionality:

react-crop-disable-crossover

**Comment by DominicTobias** [comment]
I would also like to explore keeping the crossover functionality but limited the dimensions on the other side to the available space. Trying to get something else finished this weekend so I'll look at it next week.

**Comment by DominicTobias** [comment]
Fixed in 6.0.5

**Pull request closed without merging**
