### PR TITLE
Allowed custom styles on image and wrapper elements

### PR DESCRIPTION
**Pull request by ricobl**
This PR adds the `style` and `imageStyle` props to allow custom inline styles on the `img` and on the wrapper `div`. Along with defaultProps, propTypes and docs.

I haven't updated the `dist/`, I can update the PR if the build is needed.

### CODE REVIEW

**Comment by DominicTobias** [comment]
Hi & thanks, but what's your use case for inline styles? There's some dynamic styling you're doing that you can't do using classes?

**Comment by ricobl** [comment]
Hi @DominicTobias!

There a few points in favor of inline styles:

1. we're using [material-ui](http://www.material-ui.com/) which uses inline styles everywhere, so we thought that it makes sense to follow the same approach
1. our component has an option to enable crop, when enabled it renders the `ReactCrop` component, when disabled it renders an `` element. It would be nice to share styles in these modes.

In this case, the image starts with `opacity: 0` and animates to `opacity: 1` after loaded. We could achieve the same result with CSS classes and a wrapper around the `ReactCrop` component.

**Comment by DominicTobias** [comment]
Thanks for the explanation, I'll merge it in

**Comment by ricobl** [comment]
Awesome! Thanks @DominicTobias!

Any plans to release a new version with these changes?

**Comment by junedomingo** [comment]
+1 ^

**Comment by DominicTobias** [comment]
Hi,

Sorry for the delay I’ll be back on the 10th from travelling so will
publish then

**Comment by DominicTobias** [comment]
Published in 3.0.8

**Comment by ricobl** [comment]
Thanks @DominicTobias!

**Pull request merged**
