### PR TITLE
Refactor to HOC

### PR DESCRIPTION
**Pull request by MattMcFarland**
This includes fixes from suggestions mentioned in PR #117 

 - remove extraneous `.binds()` from render
 - bind class functions used to instance in constructor.
 - add new line between `{...props}` and `{...state}`
 - add default `props` and `proptypes` to `CropSelection`
 - add documentation to readme

Some additional notes:
`eslint` did not complain the same as @DominicTobias eslint, so I think you should check and see if you have `eslint` globally installed?  If so, it might be superceding the eslint configuration for this repo.  As when I ran eslint with this repo there were many issues, to which I've fixed all of them with this final commit :+1: 

Thanks again, let me know if any issues!

### CODE REVIEW

**Comment by DominicTobias** [comment]
Good to know RE eslint, I do have it globally installed for me IDE

**Comment by DominicTobias** [comment]
Published 2.1.0

**Comment by DominicTobias** [comment]
Hey @MattMcFarland, there was a bug with the 2.1.0 release so I had to roll back, webpack would need to output 3 files to dist to get it working so I fixed it quickly by rolling back. After that I ended up doing some refactoring for v3 (main things being not keeping crop state in the component and fixing a long standing issue that was bugging me to do with the crop area continuing to expand when hitting an edge on the opposite side).

Anyway I've come to accept that I like the simplicity of it all being in one file, I think it's easier to reason about not being a HOC. Thanks for all your hard work but please make a fork instead :)

**Comment by MattMcFarland** [comment]
Hey no problem! It was a fun challenge nonetheless. I'm trying to use it
without a hoc, and i really like the changes you put in v3. As they are,
I'm finding it much easier to work with so I'm going to go without it being
a hoc anyway.

I might try to contribute again but this time unit tests.

**Pull request merged**
