### PR TITLE
Allow changing of crop property after creation

### PR DESCRIPTION
**Pull request by rcknight**
I have a use case where I need to be able to reset the crop area.
Currently changes to the crop property have no effect after component creation. This PR changes that.

### CODE REVIEW

**Comment by rcknight** [comment]
Thanks for the quick merge :) not sure about the equality thing I'm new-ish at react! Will dig into it though!

**Comment by DominicTobias** [comment]
Turns out setState does return a shallow merge https://facebook.github.io/react/docs/component-api.html#setstate. I'm doing some testing and small tweaks and will publish it soon

**Comment by DominicTobias** [comment]
@rcknight would appreciate if you have a check to see if the master branch works for your changing of props. I did a test and it does for me but please let me know how it goes before I publish, thanks!

**Comment by rcknight** [comment]
@DominicTobias looks like master works fine for me - thanks!

**Comment by rcknight** [comment]
actually - after a more thorough check I think i've found an issue, investigating

**Comment by DominicTobias** [comment]
@rcknight I must have been tired yesterday eve, I've noticed an obvious error, will look at in in about 30mins

**Comment by rcknight** [comment]
This is my test code which exhibits weird behaviour:

```
import React from 'react';
import ReactCrop from 'react-image-crop';
require('react-image-crop/dist/ReactCrop.css');

let testImage = require('../images/test.png');

var Tester = React.createClass({
  getInitialState: function() {
    var initialCrop = {
        x: 10,
        y: 10,
        width: 80,
        height: 80
    };

    return {
        crop: initialCrop
    };
  },
  render: function() {
    return (
        <div>
            <ReactCrop src={testImage} crop={this.state.crop} onComplete={this.onCropped} />
            <span>{JSON.stringify(this.state.crop)}</span>
            <button onClick={this.onReset}>Reset</button>
        </div>
    );
  },
  onCropped: function(newCrop) {
    this.setState({
        crop: newCrop
    });
  },
  onReset: function() {
    this.setState(this.getInitialState());
  }
});
```

**Comment by DominicTobias** [comment]
@rcknight Thanks for that. I've fixed one issue @ master I saw but I won't be able to test that use case until later or the weekend

**Comment by rcknight** [comment]
Latest master fixes that test case. This is good to publish now as far as I can tell :)

**Comment by DominicTobias** [comment]
Awesome thanks for checking!

**Comment by DominicTobias** [comment]
It's published @ 0.0.12

**Pull request merged**
