### PR TITLE
fix - scroll to top for IE 11

### PR DESCRIPTION
**Pull request by amankumarsaini28**

### CODE REVIEW

**Comment by amankumarsaini28** [comment]
Raised an issue for proposed fix
https://github.com/DominicTobias/react-image-crop/issues/289

**Comment by amankumarsaini28** [comment]
@DominicTobias

**Comment by DominicTobias** [comment]
Hey thanks for this, do you mind adding those comments you mentioned e.g.

```
if (this.componentRef.setActive) {
        this.componentRef.setActive(/* args */  ); // IE/Edge #289
    } else {
        this.componentRef.focus( /* args */  ); // All other browsers
    }
```

then I'll merge

**Comment by amankumarsaini28** [comment]
Updated PR with comments.
@DominicTobias

**Pull request merged**
