### PR TITLE
Build Release JS

### PR DESCRIPTION
**Pull request by littleiffel**
Hi
sorry for yet another pull request but somehow with the last i forgot to run the release task after applying the changes, so the version that is pull from npm has the correct src file, but the build is still an old one.

You could either pul this reauest or just update it yourself,

sorry and thanks

### CODE REVIEW

**Comment by DominicTobias** [comment]
Hah sorry dude rookie mistake, maybe I shouldn't have removed the commit-build check!

**Comment by DominicTobias** [comment]
PS I can't publish this until later when I'm not on my work laptop (wrong npm user)

**Comment by littleiffel** [comment]
Thanks and sorry for the trouble.

**Comment by DominicTobias** [comment]
Np, that's released now

**Comment by littleiffel** [comment]
👍

**Pull request merged**
