### PR TITLE
Center guide

### PR DESCRIPTION
**Pull request by tkienitz**

### CODE REVIEW

**Comment by DominicTobias** [comment]
I appreciate the PR but I'm not a fan of increase the API surface area for a feature only a few people might want, especially if you can solve it other ways.

I would suggest you simply do it with some CSS for example:

```css
.ReactCrop::after {
  display: block;
  position: absolute;
  border: $center-point-border;
  border-radius: 50%;
  width: $center-point-diameter;
  height: $center-point-diameter;
  top: calc(50% - (#{$center-point-diameter} / 2));
  left: calc(50% - (#{$center-point-diameter} / 2));
}
```

**Comment by virgofx** [comment]
Agreed. There's also another issue that has similar CSS if you want a circular bounding preview.

**Comment by tkienitz** [comment]
Thanks for the feedback! I had not thought of doing it purely in CSS. It was just something I wanted for my project. I have not tried forking/pull requests before and wanted to try out the process. I definitely understand not wanting to add API surface area.  Thanks for taking the time to look at it.

**Comment by DominicTobias** [comment]
Thanks! If you have trouble implementing it without adding another element let me know but it should be achievable

**Pull request closed without merging**
