### PR TITLE
Allow use of shift to increase nudge distance

### PR DESCRIPTION
**Pull request by jthistle**
I was a bit irritated by how slow nudges were, so I thought I'd implement the widely-used standard of holding shift to increase the size of a keyboard-controlled nudge. This is a control scheme used by Inkscape, pretty much all office-style applications, and a lot of other things.

This is my first PR here, so I hope I've managed to follow the correct procedures. If not, please do let me know :)

### CODE REVIEW

**Comment by DominicTobias** [comment]
Thanks for the PR I like the idea, only thing I would like to change is to put `this.state.nudgeModDown` simply on `this.nudgeModDown` since it doesn't (and shouldn't) need to trigger a re-render.

Also I need to change `e.which` to `e.key` which is deprecated, and I think that `e.shiftKey` can simply be checked and so `nudgeModDown` shouldn't be needed .-  see: https://stackoverflow.com/a/51236798/414062

**Comment by jthistle** [comment]
Interesting, I wondered if there was a way of checking if that key was pressed. I'll update my PR tommorow, thanks.

**Comment by jthistle** [comment]
Ok, should be fixed now.

**Comment by DominicTobias** [comment]
Nice! looks good thanks

**Comment by jthistle** [comment]
Thank you! And thanks for this package, it's really useful.

**Comment by DominicTobias** [comment]
Np & thanks, I will publish to npm in the next couple of days

**Pull request merged**
