### PR TITLE
Responsive image <img> element

### PR DESCRIPTION
**Pull request by JacopoDaeli**
When uploading an image bigger than the container where the cropper component is contained, the  element goes out of the container itself (my case was with bootstrap modal for example). These changes fix this problem.

Please accept these changes and update the npm module as well.

### CODE REVIEW

**Comment by DPr00f** [comment]
:/ not entirely sure if this one is needed. And if so, it would be good to not force an image to be 100% in width, cause the image could be way smaller than the container.
`max-width: 100%;` would be much better IMO.
In any case you can do 
```
.ReactCrop--image, .ReactCrop--image-copy {
    max-width: 100%;
}
```

**Comment by JacopoDaeli** [comment]
Yeah sounds even better. I will change it and open you a pull request with as well something else.

**Comment by DominicTobias** [comment]
Thanks guys. Yeah I thought about this but decided not to define it and leave it up the app's css, however I was pretty 50/50 on what do and I'm happy for max-width property as it's probably what 99% of use cases want

**Comment by JacopoDaeli** [comment]
Perfect I will open a new pull request today.
Cheers

**Comment by DominicTobias** [comment]
Thanks, I'm on holiday atm with just a phone but I've given @DPr00f access to push, though I don't think I can add him to npm without the CLI tool so publishing a new version will probably have to wait until I get back in a week

**Comment by JacopoDaeli** [comment]
Sure man, all good with that.

**Comment by DPr00f** [comment]
Thanks for adding me @DominicTobias 
We can talk about doing CI with Travis later. Then no one that contributes would need to have access to the npm. If it hits master, it will be published.

**Comment by JacopoDaeli** [comment]
@DPr00f changes done

**Comment by DPr00f** [comment]
@JacopoDaeli why did you convert all the tabs to spaces?

**Comment by JacopoDaeli** [comment]
Because you should always use spaces instead tabs with JavaScript and CSS :-)
Btw, I can reconvert to tabs if you prefer.

**Comment by DPr00f** [comment]
To be fair, I'll let Dominic approve it first as this is not my repo. I
wouldn't mind the spaces, but again, since it's not my repo, it's not my
call

**Comment by DominicTobias** [comment]
Hah, the long standing tab vs spaces debate ;) Personally I prefer tabs and
would like to keep it that way but I've had countless debates with friends
about this.

Just for the record my reason is that I never have a reason to click into
the "tab area", and pressing arrow keys jumps to the next tab position.
Also a tab is an abstraction of an indent, it means "1 indent" and that can
be whatever size you want (easier for an IDE to adjust it). My lame
technically reason is that a tab character takes 1 byte, and 4 spaces takes
4 bytes :D

**Comment by JacopoDaeli** [comment]
All right man, I will close this request and pull another tomorrow. No spaces :-)

Speak tomorrow then.

Cheers

**Pull request closed without merging**
