### PR TITLE
Fixes #134: Adding improved CDN/web support

### LINKED ISSUE #134: Add Minified Version for External Usage
Since this library is not that small and typically used only on certain pages for applications it would be nice to have a minified version for use on production sites where the file can be loaded in UMD format from a CDN.

### PR DESCRIPTION
**Pull request by virgofx**
Fixes #134: Adding support for building the release files that target web platform via UMD with both minified and unminified versions. Updated Readme with corresponding CDN information.

Once merged. I will begin the process of getting this library hosted on CDNJS (which is the best CDN) ... slightly faster then unpkg. Once that goes through, I'll submit another PR to include link on Readme.

cc @DominicTobias

### CODE REVIEW

**Comment by jimaek** [comment]
unpkg and cdnjs both use Cloudflare. So their performance is exactly the same

**Comment by virgofx** [comment]
As the backend however there are more hops when using unpkg. I believe it has to do with there Heroku server in the middle Test on similar libraries and you'll see.

**Comment by jimaek** [comment]
That only matters for 2 hits while the files are un-cached. After that the files are cached on Cloudflare and everything is exactly the same.
Anyway, just saying :)

**Comment by virgofx** [comment]
Yeah .. once cached, differences are nominal :) 

@DominicTobias  Once merged ... if you'd be so kind as to cut another release, that would be awesome. Thanks!

**Comment by DominicTobias** [comment]
Was there a reason to change `react: 'react'` to `react: 'React'`? I'm going to change it back as it's causing warnings #136

**Comment by virgofx** [comment]
Yeah because lowercase is incorrect.

The react namespace to package library name is 'react' to 'React'.

**Comment by virgofx** [comment]
We can be more specific and include all variants ... as the official documentation for webpack has it listed as:

```
  react: {
    root: 'React',
    commonjs2: 'react',
    commonjs: 'react',
    amd: 'react'
  }
```

**Comment by DominicTobias** [comment]
Cool, sounds like a good solution

**Pull request merged**
